djangoCode/proyecto/first_app/urls.py
from django.conf.urls import url
from first_app import views

#template tagging
app_name = 'first_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^crearcuenta/$',views.crearcuenta,name='crearcuenta'),
    url(r'^reservacion/$',views.reservacion,name='reservacion'),
    url(r'^inicio/$',views.inicio,name='inicio'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^$',views.index,name='index'),
    url(r'^$',views.usuarios,name='users'),
    url(r'^reservacion/$',views.selmesa,name='selmesa'),
    # url(r'^asiento/$',views.reservacion, name='asientos'),
    # url(r'^cambio/$', views.cambio, name='cambio'),
]

djangoCode/proyecto/proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from first_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout,name='logout'),
    url(r'^special/', views.special,name='special'),
    url(r'^crearcuenta/$',views.crearcuenta,name='crearcuenta'),
    url(r'^reservacion/$',views.reservacion,name='reservacion'),
    url(r'^inicio/$',views.inicio,name='inicio'),
    url(r'^user_login/$',views.user_login,name='user_login'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoCode/proyecto/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)


    #additional classes
    portfolio_site = models.URLField(blank=True,verbose_name="tu sitio con http://")

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True,verbose_name="Imagen del perfil: ")

    def __str__(self):
        return self.user.username

class Usuario(models.Model):
    nombre = models.CharField(max_length=50)
    apellidoP = models.CharField(max_length=30)
    apellidoM = models.CharField(max_length=30)
    numcta= models.CharField(max_length=10)

    def __str__(self):
        return self.nombre

class Reserva(models.Model):
    mesa = models.CharField(max_length=2,primary_key=True)
    def __str__(self):
        return self.mesa

class Asientos(models.Model):
    asiento = models.CharField(max_length=2,primary_key=True)
    status = models.BooleanField()
    mesa = models.ForeignKey(Reserva)

    def __str__(self):
        return self.asiento

class Reservaciones(models.Model):
    user = models.ForeignKey(User)
    asientos = models.ForeignKey(Asientos)
    def __str__(self):
        template = 'Reserva del usuario {0.user} asientos: {0.asientos}'
        return template.format(self)
#
# class Detalle(models.Model):
#     usuario = models.ForeignKey(Usuario)
#     reservaciones = models.ForeignKey(Reservaciones)
#     fecha = models.DateField(auto_now=True)
#     cantidad = models.IntegerField()
#     apartado = models.DecimalField(max_digits=10, decimal_places=2)
#     subtotal = models.DecimalField(max_digits=10, decimal_places=2)
#     IVA = models.DecimalField(max_digits=10, decimal_places=2)
#     total = models.DecimalField(max_digits=10, decimal_places=2)
#     def __str__(self):
#         return self.Id_Venta
# #
# class Topic(models.Model):
#     top_name = models.CharField(max_length=264,unique=True)
#
#     def __str__(self):
#         return self.top_name
#
# class Webpage(models.Model):
#     topic = models.ForeignKey(Topic)
#     name = models.CharField(max_length=264,unique=True)
#     url = models.URLField(unique=True)
#
#     def __str__(self):
#         return self.name
#
# class AccessRecord(models.Model):
#     name = models.ForeignKey(Webpage)
#     date = models.DateField()
#
#     def __str__(self):
#         return str(self.date)

djangoCode/proyecto/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import Usuario,UserProfileInfo,Asientos,Reserva
from django.contrib.auth.models import User


#validacion custom para lo que requiera en este caso z de inicio de nombre
    # if value[0].lower() != 'z':
    #     raise forms.ValidationError("Name needs to start with z")
class StatusForm(forms.ModelForm):
    class Meta():
        model = Asientos
        fields = ('asiento','status')

class ReservaForm(forms.Form):
    asiento = forms.ImageField()
    mesa = forms.ImageField()

    class Meta():
        model = Asientos
        fields = ('status')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')




class NewUser(forms.ModelForm):
    class Meta():
        model = Usuario
        fields = '__all__'
#
# class FormName(forms.Form):
#     name = forms.CharField(required=True)
#     email = forms.EmailField(required=True)
#     verifique_email = forms.EmailField(label='Ingrese su email nuevamente', required=True)
#
#     #text = forms.CharField(widget = forms.Textarea)
#     # botcacther = forms.CharField(required=False,
#     #                             widget=forms.HiddenInput,
#     #                             validators=[validators.MaxLengthValidator(0)])
#     def clean(self):
#         all_clean_data = super().clean()
#         email = all_clean_data['email']
#         vmail = all_clean_data['verifique_email']
#
#         if email != vmail:
#             raise forms.ValidationError("Asegurese que los emails son iguales")



# #manual no necesaria
#     def clean_botcatcher(self):
#         botcatcher = self.cleaned_data['botcatcher']
#         if len(botcatcher) > 0:
#             raise forms.ValidationError("Gotcha Bot!")
#         return botcatcher

djangoCode/proyecto/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from first_app.models import Usuario,Reserva,Reservaciones,Asientos,UserProfileInfo
from first_app.forms import UserForm,UserProfileInfoForm,StatusForm
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# from first_app.forms import NewUser
# Create your views here.

def index(request):
    # webpages_list = AccessRecord.objects.order_by('date')
    # date_dict = {'access_records':webpages_list}
    # Aqui se hace un diccionario donde puedes insertar con keys
    # y luego el valor que quieres instertar
    #dictionary = {'insert_me':'Hola soy de first app'}
    #return render(request,'first_app/clon.html',context=date_dict)
    return render(request,'first_app/clon.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request,"first_app/Inicio.html")
    # return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Has iniciado sesión correctamente!")

def selmesa(request):
    smesa = request.POST.get('mesa')
    asientos = Asientos.objects.filter(mesa=bar)
    return smesa

def disponible(request):
    asientos = Asientos.objects.all()

def reservacion(request):
    #bar=selmesa(request)
    mesa = request.COOKIES.get('mesa')
    print(mesa)
    asientos = Asientos.objects.filter(mesa=mesa)
    print("hola ",asientos)
    asien = request.POST.getlist('este')
    for i in asien:
        if request.method == "POST":
            estatus = Asientos.objects.get(asiento=i)
            if estatus.status == True:
                estatus.status = False
                reserva = Reservaciones(user = request.user,asientos = estatus)
                reserva.save()
            else:
                estatus.status = True
                reserva = Reservaciones(user = request.user,asientos = estatus)
                reserva.save()
            estatus.save()


    return render(request,"first_app/reservacion.html", {'asientos': asientos})


def crearcuenta(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/crearcuenta.html',
                            {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})

def inicio(request):
    return render(request,'first_app/Inicio.html')

# def crearcuenta(request):
#     return render(request,'first_app/crearcuenta.html')

def relative(request):
    return render(request,'first_app/relative_url_templates.html')

def usuarios(request):

    form = NewUser()

    if request.method == "POST":
        form = NewUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Error form invalid")

    return render(request,"first_app/crearcuenta.html",{'form':form})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return render(request,"first_app/Inicio.html")
                # return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("CUENTA NO ACTIVADA")
        else:
            print("Alguien intento ingresar pero no pudo")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Datos no validos!")
    else:
        return render(request,'first_app/user_login.html',{})


#
# def form_name_view(request):
#     form = forms.FormName()
#
#     if request.method == 'POST':
#         form = forms.FormName(request.POST)
#
#         if form.is_valid():
#             #do something code
#             print("validation success!")
#             print("NOMBRE: "+form.cleaned_data['name'])
#             print("EMAIL: "+form.cleaned_data['email'])
#             print("TEXT: "+form.cleaned_data['text'])
#
#     return render(request,'first_app/crearcuenta.html',{'form':form})

djangoCode/proyecto/templates/first_app/Inicio.html
{% extends "first_app/headfoot.html" %}
{% load static %}
{% block body_block %}

<br>


<script type="text/javascript" >
  document.getElementById('m1').addeventlistener('onclick',()=>{
    alert("alerta del post")
    let xmlhttp = new XMLHttpRequest();
    xmlhttp.open("POST", "demo_post.asp", true);
    xmlhttp.send();
  })

</script>
<!--Aqui empiezan las mesas  -->
<div class="container">

  <div class="row">
<script type="text/javascript">
  function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires="+ d.toUTCString();
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}
</script>
    <form class="" action="{% url 'first_app:selmesa' %}" method="post">
      {% csrf_token %}
      <div class="row">
      <div  class="col"><a href="{% url 'first_app:reservacion' %}" onclick="setCookie('mesa',1,1);"><img class="d-block w-100" name = "mesa" value = "1"src="{%static "/img/m1.png" %}" alt=""></a></div>

    </form>



    <div class="col"><a href="{% url 'first_app:reservacion' %}"><img class="d-block w-100" src="{%static "/img/m2.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:reservacion' %}"><img class="d-block w-100" src="{%static "/img/m3.png" %}" alt=""></a></div>
    <div class="col-3"><img class="d-block w-100" src="{%static "/img/escen.jpg" %}" alt=""></div>
    <div class="col"><a href="{% url 'first_app:reservacion' %}"><img class="d-block w-100" src="{%static "/img/m4.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:reservacion' %}"><img class="d-block w-100" src="{%static "/img/m5.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:reservacion' %}"><img class="d-block w-100" src="{%static "/img/m6.png" %}" alt=""></a></div>
  </div>
  <div class="row align-items-center">
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m7.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m8.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m9.png" %}" alt=""></a></div>
    <div class="col-3"><img class="d-block w-100" src="{%static "/img/pist.jpg" %}" alt=""></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m10.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m11.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m12.png" %}" alt=""></a></div>
  </div>
  <div class="row align-items-center">
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m13.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m14.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m15.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m16.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m17.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m18.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m19.png" %}" alt=""></a></div>
    <div class="col"><a href="{% url 'first_app:crearcuenta' %}"><img class="d-block w-100" src="{%static "/img/m20.png" %}" alt=""></a></div>
  </div>
</div>

<!--
<span>Lugares Disponibles: {{asientos.asientos}}</span> -->

{% endblock %}



    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="javauvm.js"></script>
  </body>
</html>

djangoCode/proyecto/templates/first_app/crearcuenta.html
{% extends "first_app/headfoot.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Gracias por Registrarse!</h1>
  {% else %}
    <h1>Registrate Aqui!</h1>
    <h3>LLena tus datos por favor:</h3>

    <form enctype="multipart/form-data"  method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Registrate">
    </form>
  {% endif %}
  {% endblock %}
</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

djangoCode/proyecto/templates/first_app/headfoot.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    <title>UVM | Universidad del Valle de México - UVM</title>
  </head>
  <body>
    <div class= "container">
      <!-- Inicio de NavBar  -->
    <nav class="navbar navbar-dark bg-dark border border-danger navbar-expand-lg  navbar-fixed-top ">
      <div class="container">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Aspirantes </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Estudiantes</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="#">Padres</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link disabled" href="#">Profesores</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link disabled" href="#">Organizaciones</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link disabled" href="#">Campaña 2018</a>
            </li>
          </ul>
        </div>
      </div>

</nav>
<!-- Fin de Navbar -->
<nav class="navbar navbar-light  navbar-expand-lg nav justify-content-end " style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link " href="{% url 'first_app:crearcuenta' %}">Registro</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'admin:index' %}">Administrador</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'first_app:inicio' %}">Inicio</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'first_app:user_login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
      </div>
  </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>




<!-- Footer -->
<div class="container p-3 mb-7 bg-dark text-white">
    <div class="container active text-justify text-md-justify">
      <div class="row">
        <div class="col-md-3 mt-md-0 mt-3">
          <img src="https://www.universidaduvm.mx/uvm-test-theme/images/custom/assets/img/white-uvm.png">

        </div>

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-2 mb-md-0 mb-2">

            <!-- Contáctanos -->
            <h5 class="text-capitalized"><b>Contáctanos</b></h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!" class="text-white bg-dark">01 800 0000 886</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Chats</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Buzón del rector</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Prensa UVM</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Contáctanos</a>
              </li>
            </ul>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-capitalized"><b>Links de Ayuda </b></h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!" class="text-white bg-dark">Admisiones</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Bolsa de trabajo Estudiantes </a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Centros de información UVM</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Trabaja con nosotros</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Caja y Facturación</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Mapa de Sitio</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Atención UVM</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Comunidad UVM</a>
              </li>
            </ul>
          </div>
          <!-- -->

          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-capitalized"> <b>Social Media</b></h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!" class="text-white bg-dark">Facebook</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Twitter </a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Linked in</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Youtube</a>
              </li>
              <li>
                <a href="#!" class="text-white bg-dark">Blog</a>
              </li>
            </ul>
          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-left py-3">D.R.© Universidad del Valle de México, México. 2018 Laureate International Universities
      <a href="/web/uvm/aviso-de-privacidad"> Aviso de Privacidad</a>
      |
      <a href="#"> Mapa de sitio </a>
    </div>
    <!-- Copyright -->

  </div>
  <!-- Footer -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

djangoCode/proyecto/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>relatives</title>
  </head>
  <body>

  </body>
</html>

djangoCode/proyecto/templates/first_app/reservacion.html
{% extends "first_app/headfoot.html" %}
{% load static %}
{% block body_block %}

<div class="container">
<form enctype="multipart/form-data" action="{% url 'first_app:reservacion' %}"  method="post">
  {% csrf_token %}
  <div class="row">
    {% for asiento in asientos %}
      {% if asiento.status %}
      <img src="{%static "/img/s6.jpg" %}" alt="">
      <div class="col" ><input class="d-block w-100" id= "check_box" value="{{asiento.asiento}}" name="este" type="checkbox" src="{%static "/img/s6.jpg" %}" ></div>
      {% else %}
      <img src="{%static "/img/sn6.jpg" %}" alt="">
      <div class="col" ><input class="d-block w-100" value="{{asiento.asiento}}" name="este" type="checkbox"  src="{%static "/img/s6.jpg" %}"></div>
      {% endif %}
      {% if asiento.asiento == '6' %}
      </div>
      <div class="row">
        <div class="col">        </div>
        <div class="col">  <img src="{%static "/img/ma.jpg" %}" alt="">      </div>
        <div class="col">        </div>
      </div>
      <div class="row">
      {% endif %}

    {% endfor %}
    </div>
    <input type="submit" name="" value="Reservar">
</form>
{% endblock %}



    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="javauvm.js"></script>
  </body>
</html>

djangoCode/proyecto/templates/first_app/user_login.html
{% extends 'first_app/headfoot.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Ingrese su cuenta:</h1>
  <form class="" action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Nombre de Usuario:</label>
    <input type="text" name="username" placeholder="(correo)">

    <label for="password">Password:</label>
    <input type="password" name="password" value="">

    <input type="submit" name="" value="Ingresar">

  </form>
</div>
{% endblock %}